# this stays constant over mnist & eurosat
NUM_CLASSES = 10
KERNEL_SIZE = 3
POOLING_SIZE = 2
STRIDE = 2
DROPOUT = 0.25
TRAINING_ITERATIONS = 0
BATCH_SIZE = 256
NUM_EXPERIMENTS = 1
OUT_CHANNEL = 32  # this choice is arbitrary... usually power of 2
MNL_DELTA_SCALE = 3

# mnist 
MNIST = "mnist"
MNIST_IN_CHANNEL = 1  # grayscale
MNIST_IN_FEATURE = 5408
MNIST_PATH = "./mnl/data/mnist"

# eurosat
EUROSAT = "eurosat"
EUROSAT_IN_CHANNEL = 3  # RGB
EUROSAT_IN_FEATURE = 30752
EUROSAT_PATH = "./mnl/data/eurosat"
EUROSAT_DATAPOINTS = 27000

# test constants
MNL_TEST_BETA = 1.0
MNL_TEST_EPSILON = 0.1
MNL_TEST_DELTA = 0.01
MNL_TEST_TOPK = 1
MNL_TEST_SAMPLES_FOR_SIGMA = None   # this uses all d
MNL_TEST_IMPORTANCE = False
MNL_TEST_BUDGET_IMPROVEMENT = 1.0
